fmfi-svt/anketa

src/AnketaBundle/Security/AISUserSource.php
Riesi aktualny problem s doktorandmi informatiky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/220)
=> Opravena chyba pri importovani, pokial mame ten isty predmet viackrat.

src/AnketaBundle/Resources/views/CommentReviewAdmin/index.html.twig
* Do CommentReviewAdmin pridane tlacidlo na oznacenie vsetkych
komentarov na danej strane ako zreviewovane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/221)
=> CommentReviewAdmin: Mark all as reviewed

composer.json, composer.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/228)
=> Update votru v ankete.

src/AnketaBundle/Command/ImportPredmetKatedraCommand.php
V AISe sa nieco zmenilo: Pri exporte predmet-katedra sa zmenil nazov stlpca "Skratka" na "Kod predmetu".
Funguje v arene.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/233)
=> Fix mena v tabulke z AIS.

app/config/config_local.yml.dist, src/AnketaBundle/Resources/views/Welcome/faq.html.twig
* Fix inconsitences in FAQ that arose due to its age.
* Change the link to `smernica_dekana`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/231)
=> update: Fix outdated FAQ sections

src/AnketaBundle/Command/ImportUcitelPredmetCommand.php
Pocas importu ucitelov-predmetov
Touto zmenou sa bude do konzoly vypisovat aspon nieco o tom, ake zaznamy sa nepodarilo spracovat.
Niektore detaily sa po konzultacii mozu pomenit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/234)
=> Fix ticheho preskakovania zlyhanych zaznamov 

src/AnketaBundle/Resources/views/Welcome/faq.html.twig
* Change link to `anketa` repo in FAQ (previously on Google Code, now on
GitHub)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/239)
=> update: Change link to repo in FAQ

src/AnketaBundle/Entity/UserRepository.php
Mohlo by poriesit pravidelne sa opakujuci problem s reportami (aspon docasne).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/244)
=> Pridane zistovanie department z usera, pokial to nie je v UserSeason.

src/AnketaBundle/Controller/AbstractVotingController.php, src/AnketaBundle/Integration/votr_runner.py, src/AnketaBundle/Resources/views/Hlasovanie/novote.html.twig
Pokiaľ študentovi nie je dovolené hlasovať, zobrazí sa mu zoznam
evidovaných zápisných listov (kód programu, org. jednotka).
Fixes #218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/243)
=> Informatívnejšia správa pri detekcii príslušnosti študenta.

src/AnketaBundle/Command/ImportDistribuciaZnamokCommand.php, src/AnketaBundle/Command/ImportKatedraCommand.php
Fixes #235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/242)
=> Dorobene rozne vypisy a pocitania pri roznych importoch.

app/Resources/views/base.html.twig, src/AnketaBundle/Resources/translations/messages.en.yml, src/AnketaBundle/Resources/translations/messages.sk.yml
Fixes #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/245)
=> Pridane tlacidlo s kontaktom na nas.

composer.json, composer.lock, src/AnketaBundle/Resources/translations/messages.sk.yml
* Use updated version of `votr` in both `composer.json` and
`composer.lock`.
* Revert 'not working' message in `messages.sk.yml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/254)
=> update: Use updated VOTR vesion

composer.json, composer.lock
* Pin new version of VOTR (fixes for
https://github.com/fmfi-svt/votr/issues/132)
--------------------
cc @TomiBelan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/255)
=> update: Pin new version of VOTR

src/AnketaBundle/Controller/StatisticsController.php, src/AnketaBundle/Entity/Season.php
* If we want to ignore teacher.hideAllResults
for particular Season
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/261)
=> update: added showAllResults field

src/AnketaBundle/Entity/Subject.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/262)
=> update: added fif subject fix in reports

src/AnketaBundle/Entity/Season.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/263)
=> update: set showAllResults default to 0

src/AnketaBundle/Controller/CommentReviewAdminController.php
* closes #264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/267)
=> update: role_reviewer able to review comments

app/Resources/views/base.html.twig, composer.json, src/AnketaBundle/Controller/StatisticsController.php, src/AnketaBundle/Resources/views/Statistics/displayQuestionMacro.html.twig
Implementoval som toto, ale nevedel som to otestovat kedze som nenasiel nejake rozumne pokyny ako rozbehat dev server s databazou.
Skript, ktory sa domnievam ze by mal vytrvorit nejaku DB s fake datami obsahuje len TODO, tak som predpokladal ze nefunguje.
```
reset_db () {
...
}
```
Malo by to ale vyzerat takto:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/270)
=> fix: #260, implement new google charts svg library

other/anketaFMFI.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/269)
=> update: added description of question "time spent"

composer.json, composer.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/272)
=> update: votr version from 20190924-dev

src/AnketaBundle/Resources/translations/messages.en.yml, src/AnketaBundle/Resources/translations/messages.sk.yml, src/AnketaBundle/Resources/views/Statistics/displayTeacherResponseMacro.html.twig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/273)
=> update: "thank you" button for teachers

src/AnketaBundle/Menu/HlasovanieMenu.php
* Vinko's fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/274)
=> fix: do not show submenus with zero questions

src/AnketaBundle/Menu/HlasovanieMenu.php, src/AnketaBundle/Resources/config/answer_routing.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/276)
=> update: change category order for voting

other/anketaFMFI.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/280)
=> fmfi: rewritten general questions

other/anketaPriF.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/277)
=> otazky: adjusted questions for PriF

src/AnketaBundle/Controller/ResponseController.php, src/AnketaBundle/Menu/StatisticsMenu.php, src/AnketaBundle/Resources/config/response_routing.yml, src/AnketaBundle/Resources/translations/messages.en.yml, src/AnketaBundle/Resources/translations/messages.sk.yml, src/AnketaBundle/Resources/translations/routes.en.yml, src/AnketaBundle/Resources/translations/routes.sk.yml, src/AnketaBundle/Resources/views/Response/list.html.twig
--------------------------------------------
@Sameth mozes sa prosm ta na toto pozriet?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/224)
=> Response: Stranka s listingom vsetkych odpovedi

src/AnketaBundle/Resources/translations/messages.en.yml, src/AnketaBundle/Resources/translations/messages.sk.yml, src/AnketaBundle/Resources/views/Statistics/displayTeacherResponseMacro.html.twig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/281)
=> update: adjusted automatic response texts

src/AnketaBundle/Integration/AISRetriever.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/284)
=> pass ais login/logout paths to votr runner

other/anketaFMFI_corona.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/288)
=> Fix questions for subjects

other/anketaFMFI_corona.yml
Otázky k predmetom: 8 nemá updatnutý preklad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/291)
=> Otázky FMFI 2021/22 L

app/config/config_local.yml.dist, composer.json, composer.lock, scripts/votr_export.py, scripts/votr_install.sh, src/AnketaBundle/Integration/AISRetriever.php, src/AnketaBundle/Integration/votr_runner.py
glhf @gardenerik
vyskusal som ze votr_export.py kompletne funguje
votr_runner.py samozrejme otestovany nie je, lebo este stale v IdP nie je nainstalovany andrvotr plugin, ale ked konecne bude, tiez by to snad mohlo rovno fungovat
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fmfi-svt/anketa/295)
=> Upgrade Votr and add support for Andrvotr login
